In [10]:
import numpy as np

#### Задача 1

Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите M(X), D(X).

5 вопросов
4 варианта ответа, один из 4 правильный
1/4**5
p = 1/4
1-p = 3/4


In [30]:
# 1) Вероятность угадать все вопросы. 
# k = 5 p = 1/4 (вероятность случайно выбрать првильный ответ) 1-p = 3/4 (вероятность выбрать неправильный ответ)
P_5 = (1/4)**5
P_5

0.0009765625

In [31]:
# 2) Вероятность угадать 4 вопроса из пяти. k = 4, n = 5
# P_4 = C4/5*p**4*(1-p)**(5-4)
# C4/5 = 𝑛!/𝑘!(𝑛−𝑘)!= 5!/4!(5-4)!= 5
P_4 = 5*((1/4)**4)*(3/4)
P_4

0.0146484375

In [32]:
# 3) Вероятность угадать 3 вопроса из пяти. k = 3, n = 5
# P_3 = C3/5*p**3*(1-p)**(5-3)
# C3/5 = 𝑛!/𝑘!(𝑛−𝑘)!= 5!/3!(5-3)!= 10
P_3 = 10*((1/4)**3)*((3/4)**2)
P_3

0.087890625

In [33]:
# 4) Вероятность угадать 2 вопроса из пяти. k = 2, n = 5
# P_2 = C2/5*p**2*(1-p)**(5-2)
# C2/5 = 𝑛!/𝑘!(𝑛−𝑘)!= 5!/2!(5-2)!= 10
P_2 = 10*((1/4)**2)*((3/4)**3)
P_2

0.263671875

In [34]:
# 5) Вероятность угадать 1 вопрос из пяти. k = 1, n = 5
# P_1 = C1/5*p*(1-p)**(5-1)
# C1/5 = 𝑛!/𝑘!(𝑛−𝑘)!= 5!/1!(5-1)!= 5
P_1 = 5*(1/4)*((3/4)**4)
P_1

0.3955078125

In [35]:
# 6) Вероятность не угадать ни одного вопроса из пяти. k = 0, n = 5
# P_0 = p**0*(1-p)**(5-0)
P_0 = ((1/4)**0)*((3/4)**5)
P_0

0.2373046875

In [42]:
#Математическое ожидание
x_values = np.arange(0, 6)

print(x_values)

[0 1 2 3 4 5]


In [43]:
x_probabilities = np.array([P_0, P_1, P_2, P_3, P_4, P_5])
print(sum(x_probabilities))
print(x_probabilities)

1.0
[0.23730469 0.39550781 0.26367188 0.08789062 0.01464844 0.00097656]


In [44]:
m = (x_values * x_probabilities).sum()

print(m)

1.25


Дисперсия
$$D(X) = M \left( (X - M(X))^2 \right).$$

In [45]:
y_values = x_values - m

print(y_values)

[-1.25 -0.25  0.75  1.75  2.75  3.75]


In [46]:
z_values = y_values ** 2

print(z_values)

[ 1.5625  0.0625  0.5625  3.0625  7.5625 14.0625]


In [47]:
d = (z_values * x_probabilities).sum()

print(d)

0.9375


#### Задача 2

Пользователь получает в среднем 10 писем со спамом на свой почтовый ящик за сутки. Найти число N, такое, что с вероятностью 0.95 пользователь получит не более N писем со спамом за текущий день.

$\lambda$ = 10 (10 писем в сутки)

$P(X <= N)= 0.95$ (вероятность)

$P(X <=N) = \dfrac{10^{k} e^{-10}}{k!}$

In [91]:
def poisson_proba(k: int, lambda_: float) -> float:
    """Формула Пуассона. """
    
    return (lambda_ ** k) * (np.exp(-lambda_)) / np.math.factorial(k)

Вероятность получить не более N писем предполагает получение от 0 до N писем:
$P(X \leq N) = \displaystyle\sum_{i = 0}^{N} \dfrac{10^{i} e^{-10}}{i!}$

In [92]:
sum(poisson_proba(k=i, lambda_= 10) for i in range(16)) #До просмотра вебинара, методом подбора

0.9512595966960214

In [93]:
i = -1 
p = 0
lambda_= 10
while p < 0.95:
    i += 1
    p += poisson_proba(i, lambda_)
    
i, p   

(15, 0.9512595966960214)

C вероятностью 0.95 пользователь получит не более 15 писем со спамом за текущий день. N =15

$$(X \leq 15)$$

#### Задача 3

Производятся выстрелы по мишени. Вероятность попадания в мишень при одном выстреле равна 0.01. Сколько выстрелов нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 6 раз будет совершено попадание?

Подсказка: 1) "Вероятность попасть k раз при n выстрелах" - на какое распределение это похоже? 2) А если нам нужна вероятность P(X >= k), а не P(X = k)? 3) Здесь предстоит немножко покодить.

P(x = 1) = 0.01  (1 выстрел)

P(x>=k) = 0.9

P(x<=k)= 1 - 0.9 = 0.1

k = 6 - попадание 6 раз

$$P(X = k) = C_n^k p^k (1 - p)^{n - k}$$

$$P(X \geq k) = 1 - P(X \leq k) = 1 - \displaystyle\sum_{i = 0}^{k-1}C_n^i p^i (1 - p)^{n - i}$$

In [67]:
def combinations(n: int, k: int) -> int:
    """Число сочетаний. """
    
    return np.math.factorial(n) // (np.math.factorial(k) * np.math.factorial(n - k))

In [79]:
def binom_proba(n: int, k: int, p: float) -> float:
    """Формула Бернулли. """
    
    return combinations(n, k)*(p**k)*((1-p)**(n-k))

In [82]:
def binom_proba_geq(n: int, k: int, p: float) -> float:
    """ """
    return (1 - sum(binom_proba(n, i, p) for i in range(k)))

In [90]:
p = 0.01 
P = 0
k = 6
n = 5
while P < 0.9:
    n += 1
    P = binom_proba_geq(n,k,p)
    
n,P 

(926, 0.9003627121531355)